use axum_core::response::Response;
use http::StatusCode;
use type_sets::Contains;

/// Implemented for all types that can be used as `E` inside [`ApiError<_, E>`].
///
/// implemented for [`NotFound`](crate::code::NotFound),
/// [`InternalServerError`](crate::code::InternalServerError), etc.
pub trait StatusWrapper {
    /// The status code associated with type.
    const STATUS_CODE: StatusCode;

    /// The inner value type that is wrapped by this status wrapper.
    type Inner;

    /// The pure type of this status wrapper, without any inner value.
    type Pure: StatusWrapper;

    /// Convert this status wrapper into its inner value.
    fn into_inner(self) -> Self::Inner;
}

/// Should be implemented for a type to be used as `T` inside [`ApiError<T, _>`].
pub trait ApiErrorValue {
    /// Convert the value into an axum [`Response`] with the given status code.
    ///
    /// This method must make sure that the response is valid for the given status code,
    /// and that it is consistent with the OpenAPI specification generated by
    /// [`OapiResponseFor`].
    ///
    /// # Example
    /// ```rust
    /// use axum_error_sets::{ApiErrorValue};
    /// use axum::response::{IntoResponse, Response};
    /// use http::StatusCode;
    ///
    /// struct MyErrorValue(String);
    ///
    /// impl ApiErrorValue for MyErrorValue {
    ///     fn into_response_with(self, status: StatusCode) -> Response {
    ///         (status, self.0).into_response()
    ///    }
    /// }
    /// ```
    fn into_response_with(self, status: StatusCode) -> Response;
}

/// Should be implemented for a type to be used as `T` inside [`ApiError<T, _>`], for
/// usage with [`aide`].
#[cfg(feature = "aide")]
pub trait AideApiErrorValue: ApiErrorValue {
    /// See [`aide::OperationOutput::Inner`].
    type Inner;

    /// See [`aide::OperationOutput::inferred_responses`].
    ///
    /// # Example
    /// ```rust
    /// use axum_error_sets::{ApiErrorValue, AideApiErrorValue};
    /// use axum::response::{IntoResponse, Response};
    /// use http::StatusCode;
    ///
    /// struct MyErrorValue(String);
    ///
    /// impl ApiErrorValue for MyErrorValue {
    ///     fn into_response_with(self, status: StatusCode) -> Response {
    ///         (status, self.0).into_response()
    ///    }
    /// }
    ///
    /// impl AideApiErrorValue for MyErrorValue {
    ///     type Inner = String;
    ///
    ///     fn inferred_response_for(
    ///         _ctx: &mut aide::generate::GenContext,
    ///         _operation: &mut aide::openapi::Operation,
    ///         status: StatusCode,
    ///     ) -> aide::openapi::Response {
    ///         aide::openapi::Response {
    ///             description: format!("Error: {}", status),
    ///             ..Default::default()
    ///         }
    ///     }
    /// }
    /// ```
    fn inferred_response_for(
        ctx: &mut aide::generate::GenContext,
        operation: &mut aide::openapi::Operation,
        status: StatusCode,
    ) -> aide::openapi::Response;
}

pub use api_error::*;
mod api_error;

#[cfg(feature = "aide")]
mod aide_impls;

pub mod code;

#[cfg(test)]
mod tests;

mod result_ext;
pub use result_ext::*;
